"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Sidenav from "./components/Sidenav";
import { Box } from "@mui/material";
import RightSidebar from "./components/RightSidebar";
import { DrawerProvider } from "./context/DrawerContext";
import { CartProvider } from "./context/CartContext";
import { UserProvider } from "./context/UserContext";
import { ProductProvider } from "./context/ProductContext";
import Header from "./components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  // const [rightSidebarOpen, setRightSidebarOpen] = useState(false);
  // const handleCartClick = () => {
  //   setRightSidebarOpen(true);
  // };

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{ background: "#f5f5f5" }}
      >
        <UserProvider>
          <ProductProvider>
            <CartProvider>
              <DrawerProvider>
                <Box
                  sx={
                    {
                      // display: "flex",
                      // flexDirection: { xs: "column", md: "row" }, // stack vertically on xs, horizontally on md+
                      // height: { xs: "auto", md: "100vh" }, // full viewport height on desktop, auto on mobile
                      // width: "100%",
                      // overflowX: "hidden",
                    }
                  }
                >
                  {/* <Sidenav /> */}
                  <Header />
                  <Box
                    component="main"
                    sx={{
                      flexGrow: 1,
                      width: "100%",
                      minWidth: 0, // prevents overflow
                      overflowX: "hidden",
                    }}
                  >
                    {children}
                  </Box>

                  <RightSidebar />
                </Box>
                {modal}
              </DrawerProvider>
            </CartProvider>
          </ProductProvider>
        </UserProvider>
      </body>
    </html>
  );
}
