"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidenav from "./components/Sidenav";
import { Box } from "@mui/material";
import { useState } from "react";
import RightSidebar from "./components/RightSidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  const [rightSidebarOpen, setRightSidebarOpen] = useState(false);

  const handleCartClick = () => {
    setRightSidebarOpen(true);
  };

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Box sx={{ display: "flex" }}>
          <Sidenav onCartClick={handleCartClick} />
          <Box component="main" sx={{ flexGrow: 1 }}>
            {children}
          </Box>

          <RightSidebar
            open={rightSidebarOpen}
            onClose={() => setRightSidebarOpen(false)}
          />
        </Box>
        {modal}
      </body>
    </html>
  );
}
