export const PRODUCTS = [
  {
    pr_image: "/hickoku/perfume-1.jpeg",
    pr_name: "Hickoku Luminous – A Radiant Whisper of Elegance",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-2.jpeg",
    pr_name: "Hickoku Noire – The Mystery of Midnight ",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-3.jpeg",
    pr_name: "Hickoku Fleur Royale – The Bloom of Pure Luxury",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-4.jpeg",
    pr_name: "Hickoku Ember – A Fiery Expression of Passion",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-5.jpeg",
    pr_name: "Hickoku Élan – The Essence of Fresh Sophistication",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-6.jpeg",
    pr_name: " Hickoku Velour – The Warmth of Pure Indulgence",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-7.jpeg",
    pr_name: "Hickoku Azure – A Breeze of Unrivaled Elegance",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-8.jpeg",
    pr_name: "Hickoku Rouge – A Bold Affair of Passion & Power",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-9.jpeg",
    pr_name: "Hickoku Celeste – The Scent of a Midnight Dream",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-10.jpeg",
    pr_name: " Hickoku Obsidian – The Power of Darkness & Desire",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-11.jpeg",
    pr_name: " Hickoku Lumière – The Glow of Pure Elegance",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-12.jpeg",
    pr_name: "Azzaro The Most Wanted Eau De Parfum Intense For Men",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-13.jpeg",
    pr_name: "Azzaro The Most Wanted Eau De Parfum Intense For Men",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-14.jpeg",
    pr_name: "Azzaro The Most Wanted Eau De Parfum Intense For Men",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-15.jpeg",
    pr_name: "Azzaro The Most Wanted Eau De Parfum Intense For Men",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
  {
    pr_image: "/hickoku/perfume-16.jpeg",
    pr_name: "Azzaro The Most Wanted Eau De Parfum Intense For Men",
    pr_rating: 2,
    pr_price: 2000,
    pr_size: [20, 50, 60, 100],
  },
];
